### Manual build Box64 with Github Action
name: Custom build Box64

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target platform name'
        required: true
        default: 'GENERIC_ARM'
        type: choice
        options:
        - TEST
      build_type:
        description: 'Build type'
        required: true
        default: 'RelWithDebInfo'
        type: choice
        options:
        - RelWithDebInfo
        - Release
        - Debug
        - MinSizeRel
      dynarec:
        description: 'Enable dynarec'
        required: false
        default: 'true'
        type: boolean
      trace:
        description: 'Enable trace'
        required: false
        default: 'false'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Box64 Repository"
        uses: actions/checkout@v4

      - name: "Environment preparation"
        run: |
          sudo apt-get update
          echo "BOX64_COMPILER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          sudo apt-get -y install git gcc-aarch64-linux-gnu cmake make python3

      - name: "Build Box64"
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=${{ env.BOX64_COMPILER }} -DSD845=ON\
                   -DCMAKE_BUILD_TYPE=${{ github.event.inputs.build_type }}\
                   -DARM_DYNAREC:BOOL=${{ github.event.inputs.dynarec }}\
                   -DHAVE_TRACE:BOOL=${{ github.event.inputs.trace }}\
                   -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
          make -j$(nproc) VERBOSE=1

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: box64-test
          path: build/box64



